---
name: CI – Lint YAML, Compose check, K8s validate (offline)

"on":
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: |
          yamllint . || true

  compose-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Docker compose config check
        run: |
          if [ -f docker-compose.yml ]; then
            docker compose config -q
          else
            echo "No docker-compose.yml found."
          fi

  k8s-validate:
    runs-on: ubuntu-latest
    needs: compose-check
    steps:
      - uses: actions/checkout@v4

      # ✅ ติดตั้ง kubeconform (ตรวจ K8s manifests แบบออฟไลน์)
      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
          | tar -xz kubeconform
          sudo mv kubeconform /usr/local/bin/kubeconform
          kubeconform -v

      # ✅ ตรวจไฟล์ทั้งหมดใน k8s/ (ไม่ต้องต่อคลัสเตอร์)
      - name: Validate Kubernetes manifests (offline)
        run: |
          mkdir -p reports
          if [ -d k8s ]; then
            kubeconform -strict -summary -ignore-missing-schemas k8s/ | tee reports/kubeconform.txt
          else
            echo "No k8s folder found." | tee reports/kubeconform.txt
          fi

      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: kubeconform-report
          path: reports/kubeconform.txt
