---
name: CI – Lint YAML, Compose check, K8s dry-run

"on":
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install yamllint
        run: pip install yamllint
      - name: Run yamllint
        run: |
          yamllint . || true

  compose-check:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Docker compose config check
        run: |
          if [ -f docker-compose.yml ]; then
            docker compose config -q
          else
            echo "No docker-compose.yml found."
          fi

  k8s-dryrun:
    runs-on: ubuntu-latest
    needs: compose-check
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest
      - name: K8s manifests dry-run
        run: |
          if [ -d k8s ]; then
            kubectl apply --dry-run=client -f k8s/
          else
            echo "No k8s folder found."
          fi
